baseURL: ""
languageCode: en-us
title: Datakoko
theme: datakoko

defaultContentLanguage: en
defaultContentLanguageInSubdir: false

enableRobotsTXT: true

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

params:
  description: "Build modern data infrastructure in under 30 days. DLT, dbt, DuckDB. Data sovereignty, fast deployment, cost control."
  keywords: "data infrastructure, data platform, DuckDB, dbt, DLT, self-hosted analytics, data sovereignty, GDPR compliance, data warehouse, modern data stack, ETL pipeline"
  email: "contact@datakoko.com"
  social:
    linkedin: ""
    twitter: ""
    github: ""

caches:
  images:
    dir: :cacheDir/images

languages:
  en:
    languageName: English
    contentDir: content/en
    weight: 1
    disabled: false
    menu:
      main:
        - name: Services
          pageRef: /services
          weight: 1
        - name: Approach
          pageRef: /approach
          weight: 2
        - name: Team
          pageRef: /team
          weight: 3
        - name: Contact
          pageRef: /contact
          weight: 4
  fr:
    languageName: Français
    contentDir: content/fr
    weight: 2
    disabled: false
    permalinks:
      challenges: /defis/:slug/
      benefits: /avantages/:slug/
      audit-benefits: /avantages-audit/:slug/
      process-steps: /processus-etapes/:slug/
      urgency-points: /raisons-d-agir/:slug/
      services: /services/:slug/
      team: /equipe/:slug/
    menu:
      main:
        - name: Services
          pageRef: /services
          weight: 1
        - name: Approche
          pageRef: /approach
          weight: 2
        - name: Équipe
          pageRef: /team
          weight: 3
        - name: Contact
          pageRef: /contact
          weight: 4
